//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InterLinkClass.LevelOne {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PegPayTelecomsApiSoap", Namespace="http://PegPayTelecomsApi/")]
    public partial class PegPayTelecomsApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidatePhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReversalStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountBalanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PegPayTelecomsApi() {
            this.Url = global::InterLinkClass.Properties.Settings.Default.InterLinkClass_LevelOne_PegPayTelecomsApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidatePhoneNumberCompletedEventHandler ValidatePhoneNumberCompleted;
        
        /// <remarks/>
        public event PostTransactionCompletedEventHandler PostTransactionCompleted;
        
        /// <remarks/>
        public event GetReversalStatusCompletedEventHandler GetReversalStatusCompleted;
        
        /// <remarks/>
        public event GetTransactionDetailsCompletedEventHandler GetTransactionDetailsCompleted;
        
        /// <remarks/>
        public event GetAccountBalanceCompletedEventHandler GetAccountBalanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/ValidatePhoneNumber", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelephoneNumberDetails ValidatePhoneNumber(string phoneNumber, string VendorCode, string password, string signature) {
            object[] results = this.Invoke("ValidatePhoneNumber", new object[] {
                        phoneNumber,
                        VendorCode,
                        password,
                        signature});
            return ((TelephoneNumberDetails)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePhoneNumberAsync(string phoneNumber, string VendorCode, string password, string signature) {
            this.ValidatePhoneNumberAsync(phoneNumber, VendorCode, password, signature, null);
        }
        
        /// <remarks/>
        public void ValidatePhoneNumberAsync(string phoneNumber, string VendorCode, string password, string signature, object userState) {
            if ((this.ValidatePhoneNumberOperationCompleted == null)) {
                this.ValidatePhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePhoneNumberOperationCompleted);
            }
            this.InvokeAsync("ValidatePhoneNumber", new object[] {
                        phoneNumber,
                        VendorCode,
                        password,
                        signature}, this.ValidatePhoneNumberOperationCompleted, userState);
        }
        
        private void OnValidatePhoneNumberOperationCompleted(object arg) {
            if ((this.ValidatePhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePhoneNumberCompleted(this, new ValidatePhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostTransaction", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostTransaction(Transaction trans) {
            object[] results = this.Invoke("PostTransaction", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostTransactionAsync(Transaction trans) {
            this.PostTransactionAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostTransactionAsync(Transaction trans, object userState) {
            if ((this.PostTransactionOperationCompleted == null)) {
                this.PostTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostTransactionOperationCompleted);
            }
            this.InvokeAsync("PostTransaction", new object[] {
                        trans}, this.PostTransactionOperationCompleted, userState);
        }
        
        private void OnPostTransactionOperationCompleted(object arg) {
            if ((this.PostTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostTransactionCompleted(this, new PostTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetReversalStatus", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TranDetailResponse GetReversalStatus(string VendorCode, string password, string vendorTranId) {
            object[] results = this.Invoke("GetReversalStatus", new object[] {
                        VendorCode,
                        password,
                        vendorTranId});
            return ((TranDetailResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetReversalStatusAsync(string VendorCode, string password, string vendorTranId) {
            this.GetReversalStatusAsync(VendorCode, password, vendorTranId, null);
        }
        
        /// <remarks/>
        public void GetReversalStatusAsync(string VendorCode, string password, string vendorTranId, object userState) {
            if ((this.GetReversalStatusOperationCompleted == null)) {
                this.GetReversalStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReversalStatusOperationCompleted);
            }
            this.InvokeAsync("GetReversalStatus", new object[] {
                        VendorCode,
                        password,
                        vendorTranId}, this.GetReversalStatusOperationCompleted, userState);
        }
        
        private void OnGetReversalStatusOperationCompleted(object arg) {
            if ((this.GetReversalStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReversalStatusCompleted(this, new GetReversalStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetTransactionDetails", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TranDetailResponse GetTransactionDetails(string VendorCode, string password, string vendorTranId) {
            object[] results = this.Invoke("GetTransactionDetails", new object[] {
                        VendorCode,
                        password,
                        vendorTranId});
            return ((TranDetailResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionDetailsAsync(string VendorCode, string password, string vendorTranId) {
            this.GetTransactionDetailsAsync(VendorCode, password, vendorTranId, null);
        }
        
        /// <remarks/>
        public void GetTransactionDetailsAsync(string VendorCode, string password, string vendorTranId, object userState) {
            if ((this.GetTransactionDetailsOperationCompleted == null)) {
                this.GetTransactionDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionDetailsOperationCompleted);
            }
            this.InvokeAsync("GetTransactionDetails", new object[] {
                        VendorCode,
                        password,
                        vendorTranId}, this.GetTransactionDetailsOperationCompleted, userState);
        }
        
        private void OnGetTransactionDetailsOperationCompleted(object arg) {
            if ((this.GetTransactionDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionDetailsCompleted(this, new GetTransactionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetAccountBalance", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountBalanceResponse GetAccountBalance(string vendorcode, string password) {
            object[] results = this.Invoke("GetAccountBalance", new object[] {
                        vendorcode,
                        password});
            return ((AccountBalanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountBalanceAsync(string vendorcode, string password) {
            this.GetAccountBalanceAsync(vendorcode, password, null);
        }
        
        /// <remarks/>
        public void GetAccountBalanceAsync(string vendorcode, string password, object userState) {
            if ((this.GetAccountBalanceOperationCompleted == null)) {
                this.GetAccountBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountBalanceOperationCompleted);
            }
            this.InvokeAsync("GetAccountBalance", new object[] {
                        vendorcode,
                        password}, this.GetAccountBalanceOperationCompleted, userState);
        }
        
        private void OnGetAccountBalanceOperationCompleted(object arg) {
            if ((this.GetAccountBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountBalanceCompleted(this, new GetAccountBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class TelephoneNumberDetails {
        
        private string networkField;
        
        private string nameField;
        
        private string telephonenumberField;
        
        private string isRegisteredField;
        
        private string statusField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public string Network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Telephonenumber {
            get {
                return this.telephonenumberField;
            }
            set {
                this.telephonenumberField = value;
            }
        }
        
        /// <remarks/>
        public string IsRegistered {
            get {
                return this.isRegisteredField;
            }
            set {
                this.isRegisteredField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class AccountBalanceResponse {
        
        private string balanceField;
        
        private string statusDescField;
        
        private string statusCodeField;
        
        /// <remarks/>
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class TranDetailResponse {
        
        private string pegpayIdField;
        
        private string recordDateField;
        
        private string vendorTranIdField;
        
        private string tranAmountField;
        
        private string paymentDateField;
        
        private string vendorCodeField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string telecomPostedField;
        
        private string telecomIDField;
        
        /// <remarks/>
        public string PegpayId {
            get {
                return this.pegpayIdField;
            }
            set {
                this.pegpayIdField = value;
            }
        }
        
        /// <remarks/>
        public string RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
            }
        }
        
        /// <remarks/>
        public string VendorTranId {
            get {
                return this.vendorTranIdField;
            }
            set {
                this.vendorTranIdField = value;
            }
        }
        
        /// <remarks/>
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TelecomPosted {
            get {
                return this.telecomPostedField;
            }
            set {
                this.telecomPostedField = value;
            }
        }
        
        /// <remarks/>
        public string TelecomID {
            get {
                return this.telecomIDField;
            }
            set {
                this.telecomIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class Response {
        
        private string telecomIdField;
        
        private string pegPayIdField;
        
        private string statusDescriptionField;
        
        private string statusCodeField;
        
        /// <remarks/>
        public string TelecomId {
            get {
                return this.telecomIdField;
            }
            set {
                this.telecomIdField = value;
            }
        }
        
        /// <remarks/>
        public string PegPayId {
            get {
                return this.pegPayIdField;
            }
            set {
                this.pegPayIdField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class Transaction {
        
        private string sessionIdField;
        
        private string narrationField;
        
        private string addendumDataField;
        
        private string ipField;
        
        private string digitalSignatureField;
        
        private string fromTelecomField;
        
        private string toTelecomField;
        
        private string paymentCodeField;
        
        private string vendorCodeField;
        
        private string passwordField;
        
        private string paymentDateField;
        
        private string telecomField;
        
        private string customerRefField;
        
        private string customerNameField;
        
        private string tranAmountField;
        
        private string tranChargeField;
        
        private string vendorTranIdField;
        
        private string toAccountField;
        
        private string fromAccountField;
        
        private string tranTypeField;
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
            }
        }
        
        /// <remarks/>
        public string AddendumData {
            get {
                return this.addendumDataField;
            }
            set {
                this.addendumDataField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string FromTelecom {
            get {
                return this.fromTelecomField;
            }
            set {
                this.fromTelecomField = value;
            }
        }
        
        /// <remarks/>
        public string ToTelecom {
            get {
                return this.toTelecomField;
            }
            set {
                this.toTelecomField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentCode {
            get {
                return this.paymentCodeField;
            }
            set {
                this.paymentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string Telecom {
            get {
                return this.telecomField;
            }
            set {
                this.telecomField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerRef {
            get {
                return this.customerRefField;
            }
            set {
                this.customerRefField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
            }
        }
        
        /// <remarks/>
        public string TranCharge {
            get {
                return this.tranChargeField;
            }
            set {
                this.tranChargeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorTranId {
            get {
                return this.vendorTranIdField;
            }
            set {
                this.vendorTranIdField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public string FromAccount {
            get {
                return this.fromAccountField;
            }
            set {
                this.fromAccountField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ValidatePhoneNumberCompletedEventHandler(object sender, ValidatePhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelephoneNumberDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelephoneNumberDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void PostTransactionCompletedEventHandler(object sender, PostTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetReversalStatusCompletedEventHandler(object sender, GetReversalStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReversalStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReversalStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TranDetailResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TranDetailResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetTransactionDetailsCompletedEventHandler(object sender, GetTransactionDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TranDetailResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TranDetailResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAccountBalanceCompletedEventHandler(object sender, GetAccountBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountBalanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountBalanceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591