//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.6387.
// 
#pragma warning disable 1591

namespace InterLinkClass.MessengerApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessengerSoap", Namespace="http://messenger.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Broadcast))]
    public partial class Messenger : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSBroadcastOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBroadcastStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBroadcastReceiversOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeBroadcastStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Messenger() {
            this.Url = global::InterLinkClass.Properties.Settings.Default.InterLinkClass_MessengerApi_Messenger;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBalanceCompletedEventHandler GetBalanceCompleted;
        
        /// <remarks/>
        public event PostEmailCompletedEventHandler PostEmailCompleted;
        
        /// <remarks/>
        public event GetEmailStatusCompletedEventHandler GetEmailStatusCompleted;
        
        /// <remarks/>
        public event SendSMSBroadcastCompletedEventHandler SendSMSBroadcastCompleted;
        
        /// <remarks/>
        public event GetBroadcastStatusCompletedEventHandler GetBroadcastStatusCompleted;
        
        /// <remarks/>
        public event AddBroadcastReceiversCompletedEventHandler AddBroadcastReceiversCompleted;
        
        /// <remarks/>
        public event ChangeBroadcastStatusCompletedEventHandler ChangeBroadcastStatusCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/GetBalance", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBalance(OvaAccount acct) {
            object[] results = this.Invoke("GetBalance", new object[] {
                        acct});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceAsync(OvaAccount acct) {
            this.GetBalanceAsync(acct, null);
        }
        
        /// <remarks/>
        public void GetBalanceAsync(OvaAccount acct, object userState) {
            if ((this.GetBalanceOperationCompleted == null)) {
                this.GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceOperationCompleted);
            }
            this.InvokeAsync("GetBalance", new object[] {
                        acct}, this.GetBalanceOperationCompleted, userState);
        }
        
        private void OnGetBalanceOperationCompleted(object arg) {
            if ((this.GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/PostEmail", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result PostEmail(Email email) {
            object[] results = this.Invoke("PostEmail", new object[] {
                        email});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void PostEmailAsync(Email email) {
            this.PostEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void PostEmailAsync(Email email, object userState) {
            if ((this.PostEmailOperationCompleted == null)) {
                this.PostEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostEmailOperationCompleted);
            }
            this.InvokeAsync("PostEmail", new object[] {
                        email}, this.PostEmailOperationCompleted, userState);
        }
        
        private void OnPostEmailOperationCompleted(object arg) {
            if ((this.PostEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostEmailCompleted(this, new PostEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/GetEmailStatus", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetEmailStatus(string reference) {
            object[] results = this.Invoke("GetEmailStatus", new object[] {
                        reference});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailStatusAsync(string reference) {
            this.GetEmailStatusAsync(reference, null);
        }
        
        /// <remarks/>
        public void GetEmailStatusAsync(string reference, object userState) {
            if ((this.GetEmailStatusOperationCompleted == null)) {
                this.GetEmailStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailStatusOperationCompleted);
            }
            this.InvokeAsync("GetEmailStatus", new object[] {
                        reference}, this.GetEmailStatusOperationCompleted, userState);
        }
        
        private void OnGetEmailStatusOperationCompleted(object arg) {
            if ((this.GetEmailStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailStatusCompleted(this, new GetEmailStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/SendSMSBroadcast", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SendSMSBroadcast(SmsBroadcast broadcast) {
            object[] results = this.Invoke("SendSMSBroadcast", new object[] {
                        broadcast});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSBroadcastAsync(SmsBroadcast broadcast) {
            this.SendSMSBroadcastAsync(broadcast, null);
        }
        
        /// <remarks/>
        public void SendSMSBroadcastAsync(SmsBroadcast broadcast, object userState) {
            if ((this.SendSMSBroadcastOperationCompleted == null)) {
                this.SendSMSBroadcastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSBroadcastOperationCompleted);
            }
            this.InvokeAsync("SendSMSBroadcast", new object[] {
                        broadcast}, this.SendSMSBroadcastOperationCompleted, userState);
        }
        
        private void OnSendSMSBroadcastOperationCompleted(object arg) {
            if ((this.SendSMSBroadcastCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSBroadcastCompleted(this, new SendSMSBroadcastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/GetBroadcastStatus", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BroadcastStatus GetBroadcastStatus(string reference) {
            object[] results = this.Invoke("GetBroadcastStatus", new object[] {
                        reference});
            return ((BroadcastStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetBroadcastStatusAsync(string reference) {
            this.GetBroadcastStatusAsync(reference, null);
        }
        
        /// <remarks/>
        public void GetBroadcastStatusAsync(string reference, object userState) {
            if ((this.GetBroadcastStatusOperationCompleted == null)) {
                this.GetBroadcastStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBroadcastStatusOperationCompleted);
            }
            this.InvokeAsync("GetBroadcastStatus", new object[] {
                        reference}, this.GetBroadcastStatusOperationCompleted, userState);
        }
        
        private void OnGetBroadcastStatusOperationCompleted(object arg) {
            if ((this.GetBroadcastStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBroadcastStatusCompleted(this, new GetBroadcastStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/AddBroadcastReceivers", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result AddBroadcastReceivers(Receiver[] receivers, string broadcastId) {
            object[] results = this.Invoke("AddBroadcastReceivers", new object[] {
                        receivers,
                        broadcastId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AddBroadcastReceiversAsync(Receiver[] receivers, string broadcastId) {
            this.AddBroadcastReceiversAsync(receivers, broadcastId, null);
        }
        
        /// <remarks/>
        public void AddBroadcastReceiversAsync(Receiver[] receivers, string broadcastId, object userState) {
            if ((this.AddBroadcastReceiversOperationCompleted == null)) {
                this.AddBroadcastReceiversOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBroadcastReceiversOperationCompleted);
            }
            this.InvokeAsync("AddBroadcastReceivers", new object[] {
                        receivers,
                        broadcastId}, this.AddBroadcastReceiversOperationCompleted, userState);
        }
        
        private void OnAddBroadcastReceiversOperationCompleted(object arg) {
            if ((this.AddBroadcastReceiversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBroadcastReceiversCompleted(this, new AddBroadcastReceiversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/ChangeBroadcastStatus", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result ChangeBroadcastStatus(string broadcastId, bool active) {
            object[] results = this.Invoke("ChangeBroadcastStatus", new object[] {
                        broadcastId,
                        active});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeBroadcastStatusAsync(string broadcastId, bool active) {
            this.ChangeBroadcastStatusAsync(broadcastId, active, null);
        }
        
        /// <remarks/>
        public void ChangeBroadcastStatusAsync(string broadcastId, bool active, object userState) {
            if ((this.ChangeBroadcastStatusOperationCompleted == null)) {
                this.ChangeBroadcastStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeBroadcastStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeBroadcastStatus", new object[] {
                        broadcastId,
                        active}, this.ChangeBroadcastStatusOperationCompleted, userState);
        }
        
        private void OnChangeBroadcastStatusOperationCompleted(object arg) {
            if ((this.ChangeBroadcastStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeBroadcastStatusCompleted(this, new ChangeBroadcastStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://messenger.org/SendSMS", RequestNamespace="http://messenger.org/", ResponseNamespace="http://messenger.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SendSMS(SMS sms) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        sms});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(SMS sms) {
            this.SendSMSAsync(sms, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(SMS sms, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        sms}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class OvaAccount {
        
        private string vendorField;
        
        private string balanceField;
        
        private string statusField;
        
        private string currencyField;
        
        private string senderIdField;
        
        private string spIdField;
        
        private string passwordField;
        
        private double thresholdField;
        
        /// <remarks/>
        public string Vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        public string SpId {
            get {
                return this.spIdField;
            }
            set {
                this.spIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public double Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class SMS {
        
        private string messageField;
        
        private string vendorTranIdField;
        
        private string phoneField;
        
        private string maskField;
        
        private string sentField;
        
        private string senderField;
        
        private string referenceField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string VendorTranId {
            get {
                return this.vendorTranIdField;
            }
            set {
                this.vendorTranIdField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mask {
            get {
                return this.maskField;
            }
            set {
                this.maskField = value;
            }
        }
        
        /// <remarks/>
        public string Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Receiver {
        
        private string variablesField;
        
        private string addressField;
        
        /// <remarks/>
        public string Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BroadcastStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsBroadcast))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Broadcast {
        
        private string broadcastIdField;
        
        private string subjectField;
        
        private string messageField;
        
        private string fromField;
        
        private BroadcastType broadcastTypeField;
        
        private System.Nullable<int> hourField;
        
        private string broadcastDateField;
        
        private MessageType messageTypeField;
        
        private Frequency frequencyField;
        
        /// <remarks/>
        public string BroadcastId {
            get {
                return this.broadcastIdField;
            }
            set {
                this.broadcastIdField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public BroadcastType BroadcastType {
            get {
                return this.broadcastTypeField;
            }
            set {
                this.broadcastTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        public string BroadcastDate {
            get {
                return this.broadcastDateField;
            }
            set {
                this.broadcastDateField = value;
            }
        }
        
        /// <remarks/>
        public MessageType MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public Frequency Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public enum BroadcastType {
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        EMAIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public enum MessageType {
        
        /// <remarks/>
        Generic,
        
        /// <remarks/>
        Personalised,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public enum Frequency {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        DAILY,
        
        /// <remarks/>
        WEEKLY,
        
        /// <remarks/>
        MONTHLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class BroadcastStatus : Broadcast {
        
        private int numberOfReceiversField;
        
        private string[] receiversField;
        
        private string[] broadcastDatesField;
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        public int NumberOfReceivers {
            get {
                return this.numberOfReceiversField;
            }
            set {
                this.numberOfReceiversField = value;
            }
        }
        
        /// <remarks/>
        public string[] Receivers {
            get {
                return this.receiversField;
            }
            set {
                this.receiversField = value;
            }
        }
        
        /// <remarks/>
        public string[] BroadcastDates {
            get {
                return this.broadcastDatesField;
            }
            set {
                this.broadcastDatesField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class SmsBroadcast : Broadcast {
        
        private Receiver[] receiversField;
        
        /// <remarks/>
        public Receiver[] Receivers {
            get {
                return this.receiversField;
            }
            set {
                this.receiversField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Result {
        
        private string referenceField;
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Credentials {
        
        private string usernameField;
        
        private string passwordField;
        
        private string hostField;
        
        private int portField;
        
        private bool defaultField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Attachment {
        
        private int attachmentIdField;
        
        private string attachmentNameField;
        
        private string mimeTypeField;
        
        private byte[] byteArrayField;
        
        private System.DateTime dateCreatedField;
        
        /// <remarks/>
        public int AttachmentId {
            get {
                return this.attachmentIdField;
            }
            set {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentName {
            get {
                return this.attachmentNameField;
            }
            set {
                this.attachmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ByteArray {
            get {
                return this.byteArrayField;
            }
            set {
                this.byteArrayField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class EmailAddress {
        
        private string nameField;
        
        private string addressField;
        
        private EmailAddressType addressTypeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddressType AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public enum EmailAddressType {
        
        /// <remarks/>
        To,
        
        /// <remarks/>
        CarbonCopy,
        
        /// <remarks/>
        BlindCarbonCopy,
        
        /// <remarks/>
        From,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messenger.org/")]
    public partial class Email {
        
        private string senderField;
        
        private string fromField;
        
        private string messageField;
        
        private string subjectField;
        
        private string greeetingField;
        
        private EmailAddress[] mailAddressesField;
        
        private Attachment[] attachmentsField;
        
        private Credentials credsField;
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Greeeting {
            get {
                return this.greeetingField;
            }
            set {
                this.greeetingField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress[] MailAddresses {
            get {
                return this.mailAddressesField;
            }
            set {
                this.mailAddressesField = value;
            }
        }
        
        /// <remarks/>
        public Attachment[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        public Credentials Creds {
            get {
                return this.credsField;
            }
            set {
                this.credsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetBalanceCompletedEventHandler(object sender, GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostEmailCompletedEventHandler(object sender, PostEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetEmailStatusCompletedEventHandler(object sender, GetEmailStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void SendSMSBroadcastCompletedEventHandler(object sender, SendSMSBroadcastCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSBroadcastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSBroadcastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetBroadcastStatusCompletedEventHandler(object sender, GetBroadcastStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBroadcastStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBroadcastStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BroadcastStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BroadcastStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void AddBroadcastReceiversCompletedEventHandler(object sender, AddBroadcastReceiversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBroadcastReceiversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBroadcastReceiversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void ChangeBroadcastStatusCompletedEventHandler(object sender, ChangeBroadcastStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeBroadcastStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeBroadcastStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591