//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterLinkClass.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5099/LiveLevel2PegpayTelecomsApi/PegPayTelecomsApi.asmx")]
        public string InterLinkClass_PegPayApi_PegPay {
            get {
                return ((string)(this["InterLinkClass_PegPayApi_PegPay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5099/LiveLevel2PegpayTelecomsApi/PegPayTelecomsApi.asmx")]
        public string InterLinkClass_PegpayMMoney_PegPayTelecomsApi {
            get {
                return ((string)(this["InterLinkClass_PegpayMMoney_PegPayTelecomsApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://collections.ug.airtelmoney.com/ThirdpartyPayoutLiveService/")]
        public string InterLinkClass_AirTelMoney_ThirdpartyWebServices {
            get {
                return ((string)(this["InterLinkClass_AirTelMoney_ThirdpartyWebServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:8002/LivePegPayTelecomsApi/PegPayTelecomsApi.asmx")]
        public string InterLinkClass_LevelOne_PegPayTelecomsApi {
            get {
                return ((string)(this["InterLinkClass_LevelOne_PegPayTelecomsApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.55.21:5099/MailApi/Messenger.asmx")]
        public string InterLinkClass_MessengerApi_Messenger {
            get {
                return ((string)(this["InterLinkClass_MessengerApi_Messenger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.55.21:5099/LiveDataAccess/DataAccess.asmx")]
        public string InterLinkClass_DbApi_DataAccess {
            get {
                return ((string)(this["InterLinkClass_DbApi_DataAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5099/LiveDirectToTelecomsApi/service.asmx")]
        public string InterLinkClass_D2TApi_Service {
            get {
                return ((string)(this["InterLinkClass_D2TApi_Service"]));
            }
        }
    }
}
