//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.6387.
// 
#pragma warning disable 1591

namespace InterLinkClass.D2TApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://PegPayTelecomsApi/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PostVendorToMtnWalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostDirectToAirtelMobiquityOperationCompleted;
        
        private System.Threading.SendOrPostCallback PullDirectFromAirtelMobiquityOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostVendorToMtnECWOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostVendorToAirtelWalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostVendorToUtlWalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMtnTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMtnECWTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAirtelMobiquityTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetObopayTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostDirectToAirtelObopayOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAirtelCustomerObopayOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAirtelCustomerMobiquityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountBalanceFromObopayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountBalanceFromMobiquityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::InterLinkClass.Properties.Settings.Default.InterLinkClass_D2TApi_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostVendorToMtnWalletCompletedEventHandler PostVendorToMtnWalletCompleted;
        
        /// <remarks/>
        public event PostDirectToAirtelMobiquityCompletedEventHandler PostDirectToAirtelMobiquityCompleted;
        
        /// <remarks/>
        public event PullDirectFromAirtelMobiquityCompletedEventHandler PullDirectFromAirtelMobiquityCompleted;
        
        /// <remarks/>
        public event PostVendorToMtnECWCompletedEventHandler PostVendorToMtnECWCompleted;
        
        /// <remarks/>
        public event PostVendorToAirtelWalletCompletedEventHandler PostVendorToAirtelWalletCompleted;
        
        /// <remarks/>
        public event PostVendorToUtlWalletCompletedEventHandler PostVendorToUtlWalletCompleted;
        
        /// <remarks/>
        public event GetMtnTransactionStatusCompletedEventHandler GetMtnTransactionStatusCompleted;
        
        /// <remarks/>
        public event GetMtnECWTransactionStatusCompletedEventHandler GetMtnECWTransactionStatusCompleted;
        
        /// <remarks/>
        public event GetAirtelMobiquityTransactionStatusCompletedEventHandler GetAirtelMobiquityTransactionStatusCompleted;
        
        /// <remarks/>
        public event GetObopayTransactionStatusCompletedEventHandler GetObopayTransactionStatusCompleted;
        
        /// <remarks/>
        public event PostDirectToAirtelObopayCompletedEventHandler PostDirectToAirtelObopayCompleted;
        
        /// <remarks/>
        public event VerifyAirtelCustomerObopayCompletedEventHandler VerifyAirtelCustomerObopayCompleted;
        
        /// <remarks/>
        public event VerifyAirtelCustomerMobiquityCompletedEventHandler VerifyAirtelCustomerMobiquityCompleted;
        
        /// <remarks/>
        public event GetAccountBalanceFromObopayCompletedEventHandler GetAccountBalanceFromObopayCompleted;
        
        /// <remarks/>
        public event GetAccountBalanceFromMobiquityCompletedEventHandler GetAccountBalanceFromMobiquityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostVendorToMtnWallet", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostVendorToMtnWallet(Transaction trans) {
            object[] results = this.Invoke("PostVendorToMtnWallet", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostVendorToMtnWalletAsync(Transaction trans) {
            this.PostVendorToMtnWalletAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostVendorToMtnWalletAsync(Transaction trans, object userState) {
            if ((this.PostVendorToMtnWalletOperationCompleted == null)) {
                this.PostVendorToMtnWalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostVendorToMtnWalletOperationCompleted);
            }
            this.InvokeAsync("PostVendorToMtnWallet", new object[] {
                        trans}, this.PostVendorToMtnWalletOperationCompleted, userState);
        }
        
        private void OnPostVendorToMtnWalletOperationCompleted(object arg) {
            if ((this.PostVendorToMtnWalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostVendorToMtnWalletCompleted(this, new PostVendorToMtnWalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostDirectToAirtelMobiquity", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostDirectToAirtelMobiquity(Transaction trans) {
            object[] results = this.Invoke("PostDirectToAirtelMobiquity", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostDirectToAirtelMobiquityAsync(Transaction trans) {
            this.PostDirectToAirtelMobiquityAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostDirectToAirtelMobiquityAsync(Transaction trans, object userState) {
            if ((this.PostDirectToAirtelMobiquityOperationCompleted == null)) {
                this.PostDirectToAirtelMobiquityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostDirectToAirtelMobiquityOperationCompleted);
            }
            this.InvokeAsync("PostDirectToAirtelMobiquity", new object[] {
                        trans}, this.PostDirectToAirtelMobiquityOperationCompleted, userState);
        }
        
        private void OnPostDirectToAirtelMobiquityOperationCompleted(object arg) {
            if ((this.PostDirectToAirtelMobiquityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostDirectToAirtelMobiquityCompleted(this, new PostDirectToAirtelMobiquityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PullDirectFromAirtelMobiquity", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PullDirectFromAirtelMobiquity(Transaction trans) {
            object[] results = this.Invoke("PullDirectFromAirtelMobiquity", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PullDirectFromAirtelMobiquityAsync(Transaction trans) {
            this.PullDirectFromAirtelMobiquityAsync(trans, null);
        }
        
        /// <remarks/>
        public void PullDirectFromAirtelMobiquityAsync(Transaction trans, object userState) {
            if ((this.PullDirectFromAirtelMobiquityOperationCompleted == null)) {
                this.PullDirectFromAirtelMobiquityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPullDirectFromAirtelMobiquityOperationCompleted);
            }
            this.InvokeAsync("PullDirectFromAirtelMobiquity", new object[] {
                        trans}, this.PullDirectFromAirtelMobiquityOperationCompleted, userState);
        }
        
        private void OnPullDirectFromAirtelMobiquityOperationCompleted(object arg) {
            if ((this.PullDirectFromAirtelMobiquityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PullDirectFromAirtelMobiquityCompleted(this, new PullDirectFromAirtelMobiquityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostVendorToMtnECW", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostVendorToMtnECW(Transaction trans) {
            object[] results = this.Invoke("PostVendorToMtnECW", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostVendorToMtnECWAsync(Transaction trans) {
            this.PostVendorToMtnECWAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostVendorToMtnECWAsync(Transaction trans, object userState) {
            if ((this.PostVendorToMtnECWOperationCompleted == null)) {
                this.PostVendorToMtnECWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostVendorToMtnECWOperationCompleted);
            }
            this.InvokeAsync("PostVendorToMtnECW", new object[] {
                        trans}, this.PostVendorToMtnECWOperationCompleted, userState);
        }
        
        private void OnPostVendorToMtnECWOperationCompleted(object arg) {
            if ((this.PostVendorToMtnECWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostVendorToMtnECWCompleted(this, new PostVendorToMtnECWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostVendorToAirtelWallet", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostVendorToAirtelWallet(Transaction trans) {
            object[] results = this.Invoke("PostVendorToAirtelWallet", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostVendorToAirtelWalletAsync(Transaction trans) {
            this.PostVendorToAirtelWalletAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostVendorToAirtelWalletAsync(Transaction trans, object userState) {
            if ((this.PostVendorToAirtelWalletOperationCompleted == null)) {
                this.PostVendorToAirtelWalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostVendorToAirtelWalletOperationCompleted);
            }
            this.InvokeAsync("PostVendorToAirtelWallet", new object[] {
                        trans}, this.PostVendorToAirtelWalletOperationCompleted, userState);
        }
        
        private void OnPostVendorToAirtelWalletOperationCompleted(object arg) {
            if ((this.PostVendorToAirtelWalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostVendorToAirtelWalletCompleted(this, new PostVendorToAirtelWalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostVendorToUtlWallet", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostVendorToUtlWallet(Transaction trans) {
            object[] results = this.Invoke("PostVendorToUtlWallet", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostVendorToUtlWalletAsync(Transaction trans) {
            this.PostVendorToUtlWalletAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostVendorToUtlWalletAsync(Transaction trans, object userState) {
            if ((this.PostVendorToUtlWalletOperationCompleted == null)) {
                this.PostVendorToUtlWalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostVendorToUtlWalletOperationCompleted);
            }
            this.InvokeAsync("PostVendorToUtlWallet", new object[] {
                        trans}, this.PostVendorToUtlWalletOperationCompleted, userState);
        }
        
        private void OnPostVendorToUtlWalletOperationCompleted(object arg) {
            if ((this.PostVendorToUtlWalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostVendorToUtlWalletCompleted(this, new PostVendorToUtlWalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetMtnTransactionStatus", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetMtnTransactionStatus(Transaction trans) {
            object[] results = this.Invoke("GetMtnTransactionStatus", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetMtnTransactionStatusAsync(Transaction trans) {
            this.GetMtnTransactionStatusAsync(trans, null);
        }
        
        /// <remarks/>
        public void GetMtnTransactionStatusAsync(Transaction trans, object userState) {
            if ((this.GetMtnTransactionStatusOperationCompleted == null)) {
                this.GetMtnTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMtnTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetMtnTransactionStatus", new object[] {
                        trans}, this.GetMtnTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetMtnTransactionStatusOperationCompleted(object arg) {
            if ((this.GetMtnTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMtnTransactionStatusCompleted(this, new GetMtnTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetMtnECWTransactionStatus", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetMtnECWTransactionStatus(Transaction trans) {
            object[] results = this.Invoke("GetMtnECWTransactionStatus", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetMtnECWTransactionStatusAsync(Transaction trans) {
            this.GetMtnECWTransactionStatusAsync(trans, null);
        }
        
        /// <remarks/>
        public void GetMtnECWTransactionStatusAsync(Transaction trans, object userState) {
            if ((this.GetMtnECWTransactionStatusOperationCompleted == null)) {
                this.GetMtnECWTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMtnECWTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetMtnECWTransactionStatus", new object[] {
                        trans}, this.GetMtnECWTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetMtnECWTransactionStatusOperationCompleted(object arg) {
            if ((this.GetMtnECWTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMtnECWTransactionStatusCompleted(this, new GetMtnECWTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetAirtelMobiquityTransactionStatus", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetAirtelMobiquityTransactionStatus(Transaction trans) {
            object[] results = this.Invoke("GetAirtelMobiquityTransactionStatus", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetAirtelMobiquityTransactionStatusAsync(Transaction trans) {
            this.GetAirtelMobiquityTransactionStatusAsync(trans, null);
        }
        
        /// <remarks/>
        public void GetAirtelMobiquityTransactionStatusAsync(Transaction trans, object userState) {
            if ((this.GetAirtelMobiquityTransactionStatusOperationCompleted == null)) {
                this.GetAirtelMobiquityTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirtelMobiquityTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetAirtelMobiquityTransactionStatus", new object[] {
                        trans}, this.GetAirtelMobiquityTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetAirtelMobiquityTransactionStatusOperationCompleted(object arg) {
            if ((this.GetAirtelMobiquityTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirtelMobiquityTransactionStatusCompleted(this, new GetAirtelMobiquityTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetObopayTransactionStatus", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetObopayTransactionStatus(Transaction trans) {
            object[] results = this.Invoke("GetObopayTransactionStatus", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetObopayTransactionStatusAsync(Transaction trans) {
            this.GetObopayTransactionStatusAsync(trans, null);
        }
        
        /// <remarks/>
        public void GetObopayTransactionStatusAsync(Transaction trans, object userState) {
            if ((this.GetObopayTransactionStatusOperationCompleted == null)) {
                this.GetObopayTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObopayTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetObopayTransactionStatus", new object[] {
                        trans}, this.GetObopayTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetObopayTransactionStatusOperationCompleted(object arg) {
            if ((this.GetObopayTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObopayTransactionStatusCompleted(this, new GetObopayTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/PostDirectToAirtelObopay", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostDirectToAirtelObopay(Transaction trans) {
            object[] results = this.Invoke("PostDirectToAirtelObopay", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostDirectToAirtelObopayAsync(Transaction trans) {
            this.PostDirectToAirtelObopayAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostDirectToAirtelObopayAsync(Transaction trans, object userState) {
            if ((this.PostDirectToAirtelObopayOperationCompleted == null)) {
                this.PostDirectToAirtelObopayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostDirectToAirtelObopayOperationCompleted);
            }
            this.InvokeAsync("PostDirectToAirtelObopay", new object[] {
                        trans}, this.PostDirectToAirtelObopayOperationCompleted, userState);
        }
        
        private void OnPostDirectToAirtelObopayOperationCompleted(object arg) {
            if ((this.PostDirectToAirtelObopayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostDirectToAirtelObopayCompleted(this, new PostDirectToAirtelObopayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/VerifyAirtelCustomerObopay", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelecomCustomer VerifyAirtelCustomerObopay(Transaction tran) {
            object[] results = this.Invoke("VerifyAirtelCustomerObopay", new object[] {
                        tran});
            return ((TelecomCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAirtelCustomerObopayAsync(Transaction tran) {
            this.VerifyAirtelCustomerObopayAsync(tran, null);
        }
        
        /// <remarks/>
        public void VerifyAirtelCustomerObopayAsync(Transaction tran, object userState) {
            if ((this.VerifyAirtelCustomerObopayOperationCompleted == null)) {
                this.VerifyAirtelCustomerObopayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAirtelCustomerObopayOperationCompleted);
            }
            this.InvokeAsync("VerifyAirtelCustomerObopay", new object[] {
                        tran}, this.VerifyAirtelCustomerObopayOperationCompleted, userState);
        }
        
        private void OnVerifyAirtelCustomerObopayOperationCompleted(object arg) {
            if ((this.VerifyAirtelCustomerObopayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAirtelCustomerObopayCompleted(this, new VerifyAirtelCustomerObopayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/VerifyAirtelCustomerMobiquity", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelecomCustomer VerifyAirtelCustomerMobiquity(Transaction tran) {
            object[] results = this.Invoke("VerifyAirtelCustomerMobiquity", new object[] {
                        tran});
            return ((TelecomCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAirtelCustomerMobiquityAsync(Transaction tran) {
            this.VerifyAirtelCustomerMobiquityAsync(tran, null);
        }
        
        /// <remarks/>
        public void VerifyAirtelCustomerMobiquityAsync(Transaction tran, object userState) {
            if ((this.VerifyAirtelCustomerMobiquityOperationCompleted == null)) {
                this.VerifyAirtelCustomerMobiquityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAirtelCustomerMobiquityOperationCompleted);
            }
            this.InvokeAsync("VerifyAirtelCustomerMobiquity", new object[] {
                        tran}, this.VerifyAirtelCustomerMobiquityOperationCompleted, userState);
        }
        
        private void OnVerifyAirtelCustomerMobiquityOperationCompleted(object arg) {
            if ((this.VerifyAirtelCustomerMobiquityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAirtelCustomerMobiquityCompleted(this, new VerifyAirtelCustomerMobiquityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetAccountBalanceFromObopay", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelecomCustomer GetAccountBalanceFromObopay(Transaction tran) {
            object[] results = this.Invoke("GetAccountBalanceFromObopay", new object[] {
                        tran});
            return ((TelecomCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountBalanceFromObopayAsync(Transaction tran) {
            this.GetAccountBalanceFromObopayAsync(tran, null);
        }
        
        /// <remarks/>
        public void GetAccountBalanceFromObopayAsync(Transaction tran, object userState) {
            if ((this.GetAccountBalanceFromObopayOperationCompleted == null)) {
                this.GetAccountBalanceFromObopayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountBalanceFromObopayOperationCompleted);
            }
            this.InvokeAsync("GetAccountBalanceFromObopay", new object[] {
                        tran}, this.GetAccountBalanceFromObopayOperationCompleted, userState);
        }
        
        private void OnGetAccountBalanceFromObopayOperationCompleted(object arg) {
            if ((this.GetAccountBalanceFromObopayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountBalanceFromObopayCompleted(this, new GetAccountBalanceFromObopayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayTelecomsApi/GetAccountBalanceFromMobiquity", RequestNamespace="http://PegPayTelecomsApi/", ResponseNamespace="http://PegPayTelecomsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetAccountBalanceFromMobiquity(Transaction tran) {
            object[] results = this.Invoke("GetAccountBalanceFromMobiquity", new object[] {
                        tran});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountBalanceFromMobiquityAsync(Transaction tran) {
            this.GetAccountBalanceFromMobiquityAsync(tran, null);
        }
        
        /// <remarks/>
        public void GetAccountBalanceFromMobiquityAsync(Transaction tran, object userState) {
            if ((this.GetAccountBalanceFromMobiquityOperationCompleted == null)) {
                this.GetAccountBalanceFromMobiquityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountBalanceFromMobiquityOperationCompleted);
            }
            this.InvokeAsync("GetAccountBalanceFromMobiquity", new object[] {
                        tran}, this.GetAccountBalanceFromMobiquityOperationCompleted, userState);
        }
        
        private void OnGetAccountBalanceFromMobiquityOperationCompleted(object arg) {
            if ((this.GetAccountBalanceFromMobiquityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountBalanceFromMobiquityCompleted(this, new GetAccountBalanceFromMobiquityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class Transaction {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        private string tranNarrationField;
        
        private string pegPayIdField;
        
        private string transactingOvaField;
        
        private Charges chargesField;
        
        private string digitalSignatureField;
        
        private string fromTelecomField;
        
        private string toTelecomField;
        
        private string paymentCodeField;
        
        private string vendorCodeField;
        
        private string passwordField;
        
        private string paymentDateField;
        
        private string telecomField;
        
        private string customerRefField;
        
        private string customerNameField;
        
        private string tranAmountField;
        
        private string tranChargeField;
        
        private string vendorTranIdField;
        
        private string toAccountField;
        
        private string fromAccountField;
        
        private string tranTypeField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
        
        /// <remarks/>
        public string TranNarration {
            get {
                return this.tranNarrationField;
            }
            set {
                this.tranNarrationField = value;
            }
        }
        
        /// <remarks/>
        public string PegPayId {
            get {
                return this.pegPayIdField;
            }
            set {
                this.pegPayIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactingOva {
            get {
                return this.transactingOvaField;
            }
            set {
                this.transactingOvaField = value;
            }
        }
        
        /// <remarks/>
        public Charges Charges {
            get {
                return this.chargesField;
            }
            set {
                this.chargesField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string FromTelecom {
            get {
                return this.fromTelecomField;
            }
            set {
                this.fromTelecomField = value;
            }
        }
        
        /// <remarks/>
        public string ToTelecom {
            get {
                return this.toTelecomField;
            }
            set {
                this.toTelecomField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentCode {
            get {
                return this.paymentCodeField;
            }
            set {
                this.paymentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string Telecom {
            get {
                return this.telecomField;
            }
            set {
                this.telecomField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerRef {
            get {
                return this.customerRefField;
            }
            set {
                this.customerRefField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
            }
        }
        
        /// <remarks/>
        public string TranCharge {
            get {
                return this.tranChargeField;
            }
            set {
                this.tranChargeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorTranId {
            get {
                return this.vendorTranIdField;
            }
            set {
                this.vendorTranIdField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public string FromAccount {
            get {
                return this.fromAccountField;
            }
            set {
                this.fromAccountField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class Charges {
        
        private string pegasusCommisionAccountField;
        
        private string telecomCommissionAccountField;
        
        private string cashoutAccountField;
        
        private double pegasusCommissionField;
        
        private double telecomChargeField;
        
        private double cashOutChargeField;
        
        /// <remarks/>
        public string PegasusCommisionAccount {
            get {
                return this.pegasusCommisionAccountField;
            }
            set {
                this.pegasusCommisionAccountField = value;
            }
        }
        
        /// <remarks/>
        public string TelecomCommissionAccount {
            get {
                return this.telecomCommissionAccountField;
            }
            set {
                this.telecomCommissionAccountField = value;
            }
        }
        
        /// <remarks/>
        public string CashoutAccount {
            get {
                return this.cashoutAccountField;
            }
            set {
                this.cashoutAccountField = value;
            }
        }
        
        /// <remarks/>
        public double PegasusCommission {
            get {
                return this.pegasusCommissionField;
            }
            set {
                this.pegasusCommissionField = value;
            }
        }
        
        /// <remarks/>
        public double TelecomCharge {
            get {
                return this.telecomChargeField;
            }
            set {
                this.telecomChargeField = value;
            }
        }
        
        /// <remarks/>
        public double CashOutCharge {
            get {
                return this.cashOutChargeField;
            }
            set {
                this.cashOutChargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class TelecomCustomer {
        
        private string statusDescField;
        
        private string telecomField;
        
        private string statusCodeField;
        
        private string isEnabledForMobileMoneyField;
        
        private string customerTelField;
        
        private string customerNameField;
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
        
        /// <remarks/>
        public string Telecom {
            get {
                return this.telecomField;
            }
            set {
                this.telecomField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IsEnabledForMobileMoney {
            get {
                return this.isEnabledForMobileMoneyField;
            }
            set {
                this.isEnabledForMobileMoneyField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTel {
            get {
                return this.customerTelField;
            }
            set {
                this.customerTelField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6387")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayTelecomsApi/")]
    public partial class Response {
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string telecomIdField;
        
        private string pegPayIdField;
        
        private string transactingOvaField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TelecomId {
            get {
                return this.telecomIdField;
            }
            set {
                this.telecomIdField = value;
            }
        }
        
        /// <remarks/>
        public string PegPayId {
            get {
                return this.pegPayIdField;
            }
            set {
                this.pegPayIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactingOva {
            get {
                return this.transactingOvaField;
            }
            set {
                this.transactingOvaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostVendorToMtnWalletCompletedEventHandler(object sender, PostVendorToMtnWalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostVendorToMtnWalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostVendorToMtnWalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostDirectToAirtelMobiquityCompletedEventHandler(object sender, PostDirectToAirtelMobiquityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostDirectToAirtelMobiquityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostDirectToAirtelMobiquityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PullDirectFromAirtelMobiquityCompletedEventHandler(object sender, PullDirectFromAirtelMobiquityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PullDirectFromAirtelMobiquityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PullDirectFromAirtelMobiquityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostVendorToMtnECWCompletedEventHandler(object sender, PostVendorToMtnECWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostVendorToMtnECWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostVendorToMtnECWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostVendorToAirtelWalletCompletedEventHandler(object sender, PostVendorToAirtelWalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostVendorToAirtelWalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostVendorToAirtelWalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostVendorToUtlWalletCompletedEventHandler(object sender, PostVendorToUtlWalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostVendorToUtlWalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostVendorToUtlWalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetMtnTransactionStatusCompletedEventHandler(object sender, GetMtnTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMtnTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMtnTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetMtnECWTransactionStatusCompletedEventHandler(object sender, GetMtnECWTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMtnECWTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMtnECWTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetAirtelMobiquityTransactionStatusCompletedEventHandler(object sender, GetAirtelMobiquityTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirtelMobiquityTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirtelMobiquityTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetObopayTransactionStatusCompletedEventHandler(object sender, GetObopayTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObopayTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObopayTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void PostDirectToAirtelObopayCompletedEventHandler(object sender, PostDirectToAirtelObopayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostDirectToAirtelObopayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostDirectToAirtelObopayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void VerifyAirtelCustomerObopayCompletedEventHandler(object sender, VerifyAirtelCustomerObopayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAirtelCustomerObopayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAirtelCustomerObopayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelecomCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelecomCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void VerifyAirtelCustomerMobiquityCompletedEventHandler(object sender, VerifyAirtelCustomerMobiquityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAirtelCustomerMobiquityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAirtelCustomerMobiquityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelecomCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelecomCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetAccountBalanceFromObopayCompletedEventHandler(object sender, GetAccountBalanceFromObopayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountBalanceFromObopayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountBalanceFromObopayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelecomCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelecomCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetAccountBalanceFromMobiquityCompletedEventHandler(object sender, GetAccountBalanceFromMobiquityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountBalanceFromMobiquityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountBalanceFromMobiquityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591